theme: jekyll-theme-minimal
github: [metadata]

google_analytics: UA-36685415-1

title: Michael R. Bock
twitter_url: https://twitter.com/michaelrbock
medium_url: https://medium.com/@michaelrbock
github_url: https://github.com/michaelrbock
linkedin_url: https://www.linkedin.com/in/michaelrbock
quora_url: https://www.quora.com/profile/Michael-Bock-1
hn_url: https://news.ycombinator.com/user?id=michaelrbock
ph_url: https://www.producthunt.com/@michaelrbock
